import express from 'express';
import path from 'path';
import http from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { createServer as createViteServer } from 'vite';
import { readAssignments, addAssignment, deleteAssignment, getAssignment, updateAssignment } from './server/db';
import { queueJob, subscribeToJob, unsubscribeFromJob, unsubscribeFromAllJobs, getGeminiClient } from './server/queue';
import dotenv from 'dotenv';

dotenv.config();

async function start() {
  const app = express();
  app.use(express.json({ limit: '50mb' })); // support larger file transcripts

  // API endpoints
  app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', time: new Date().toISOString() });
  });

  app.get('/api/assignments', (req, res) => {
    res.json(readAssignments());
  });

  app.get('/api/assignments/:id', (req, res) => {
    const item = getAssignment(req.params.id);
    if (!item) return res.status(404).json({ error: 'Assignment not found' });
    res.json(item);
  });

  app.post('/api/assignments', (req, res) => {
    const { title, subject, className, dueDate, questionTypes, additionalInfo, fileName, fileContent } = req.body;
    
    if (!title || !subject || !className || !dueDate || !questionTypes || !Array.isArray(questionTypes)) {
      return res.status(400).json({ error: 'Please enter all details including due date.' });
    }

    let totalQuestions = 0;
    let totalMarks = 0;
    for (const qt of questionTypes) {
      if (!qt.type || qt.count <= 0 || qt.marks <= 0) {
        return res.status(400).json({ error: 'Questions counts and marks must be positive values.' });
      }
      totalQuestions += Number(qt.count);
      totalMarks += Number(qt.count) * Number(qt.marks);
    }

    const assignmentId = 'a_' + Math.random().toString(36).substring(2, 9);
    const newAssignment = {
      id: assignmentId,
      title,
      subject,
      className,
      dueDate,
      questionTypes,
      additionalInfo: additionalInfo || '',
      status: 'pending' as const,
      progressMsg: 'In queue: Waiting to write job schedule...',
      fileName: fileName || undefined,
      fileContent: fileContent || undefined,
      totalQuestions,
      totalMarks,
      createdAt: new Date().toISOString()
    };

    addAssignment(newAssignment);
    queueJob(assignmentId);

    res.status(201).json(newAssignment);
  });

  app.post('/api/assignments/:id/regenerate', (req, res) => {
    const { id } = req.params;
    const item = getAssignment(id);
    if (!item) return res.status(404).json({ error: 'Assignment not found' });

    updateAssignment(id, {
      status: 'pending',
      progressMsg: 'Re-queuing evaluation parameters...',
      generatedPaper: undefined
    });

    queueJob(id);
    res.json({ success: true, message: 'Assignment successfully requeued' });
  });

  app.delete('/api/assignments/:id', (req, res) => {
    const success = deleteAssignment(req.params.id);
    if (!success) return res.status(404).json({ error: 'Assignment not found' });
    res.json({ success: true });
  });

  app.post('/api/ai/generate', async (req, res) => {
    const { prompt, systemInstruction } = req.body;
    if (!prompt) return res.status(400).json({ error: 'Prompt is required' });

    const ai = getGeminiClient();
    try {
      if (ai) {
        console.log('Using live Gemini Client for Quick Toolkit action:', prompt);
        const response = await ai.models.generateContent({
          model: 'gemini-3.5-flash',
          contents: prompt,
          config: {
            systemInstruction: systemInstruction || 'You are an expert school curriculum designer.'
          }
        });
        res.json({ text: response.text });
      } else {
        console.log('API key missing - using deep curation local fallback values for Quick Toolkit');
        let stubResponse = "Here is a curated curriculum guideline generated by VedaAI:\n\n";
        const lowPrompt = prompt.toLowerCase();
        
        if (lowPrompt.includes('rubric')) {
          stubResponse += `### CBSE Evaluation Rubric Matrix\n\n| Criteria | Exemplary (4 pts) | Proficient (3 pts) | Basic (2 pts) | Novice (1 pt) |\n| :--- | :--- | :--- | :--- | :--- |\n| **Depth of understanding** | Synthesizes complex evidence with outstanding context (CBSE Standard). | Clear evidence of critical synthesis and textbook referencing. | Explains basic factors with minor errors in chapter scope. | Unable to identify key evidence. |\n| **Clarity & Flow** | Prose has precise structure and pristine display typography. | Well-organized with few structural issues. | Intelligible sentences but layout wanders. | Disorganized with severe spelling mistakes. |`;
        } else if (lowPrompt.includes('grading') || lowPrompt.includes('grade')) {
          stubResponse += `### AI Grading Suggestion Sheet & Feedback\n\n- **Score Range**: 18/20 (Grade: A-)\n- **Strengths**: Student demonstrates high analytical mastery over primary ecosystem food chains. Calculation methods for ecological carrying capacities are 100% correct.\n- **Improvement Areas**: Suggest revising chemical bonding definitions in Chapter Section 4.`;
        } else if (lowPrompt.includes('syllabus')) {
          stubResponse += `### CBSE Lesson Plan Schedule Outline\n\n- **Week 1-2**: Chapter 1 - Foundations of Cell Division & Mitosis. Homework: Draw diagram leaf structures.\n- **Week 3-4**: Chapter 2 - Photosynthesis respiration loops. Fieldwork: Measure CO2 output.`;
        } else {
          stubResponse += `### 10-Question Comprehensive Bank (DPS Curation)\n\n1. Explain the differences between animal cells and plant cells under high contrast microscope settings.\n2. Detail the biochemical steps of cellular respiration cycles.\n3. Compare and contrast kinetic potential energy matrices.\n4. Design an experiment demonstrating molecular evaporation rates.\n5. What is the fundamental function of Mitochondria in eukaryotic cells?`;
        }
        res.json({ text: stubResponse });
      }
    } catch (err: any) {
      console.error('API Error in toolkit generation:', err);
      res.status(500).json({ error: err.message });
    }
  });

  // Setup dual HTTP + WebSocket server
  const httpServer = http.createServer(app);
  const wss = new WebSocketServer({ noServer: true });

  wss.on('connection', (ws: WebSocket) => {
    console.log('WS connection received');
    
    ws.on('message', (message) => {
      try {
        const payload = JSON.parse(message.toString());
        console.log('WS received operation:', payload);
        
        if (payload.type === 'subscribe') {
          subscribeToJob(payload.jobId, ws);
        } else if (payload.type === 'unsubscribe') {
          unsubscribeFromJob(payload.jobId, ws);
        }
      } catch (err) {
        console.error('Error processing WS command:', err);
      }
    });

    ws.on('close', () => {
      console.log('WS client disconnected');
      unsubscribeFromAllJobs(ws);
    });
  });

  // Handle upgrade protocol
  httpServer.on('upgrade', (request, socket, head) => {
    const location = new URL(request.url || '', `http://${request.headers.host}`);
    const pathname = location.pathname;
    
    if (pathname === '/api/ws') {
      wss.handleUpgrade(request, socket, head, (ws) => {
        wss.emit('connection', ws, request);
      });
    } else {
      socket.destroy();
    }
  });

  // Serve static assets using Vite in dev vs static serving in prod
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  const PORT = 3000;
  httpServer.listen(PORT, '0.0.0.0', () => {
    console.log(`Server launched successfully on port ${PORT}`);
  });
}

start().catch((err) => {
  console.error('Error launching application server:', err);
});
